### ISSUE TITLE
add loading indicator to train model button

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#102]

**Comment by TobiasRoeddiger** [comment]
deactivate the button while processing

**Comment by KtrauM** [comment]
What is the expected behaviour:
1) when the user refreshes the page,
2) when they change the training configuration (model, labels, sensors, hyperparameters),
3) when they are still on the model page but the current training finishes?

If the button remains deactivated for 1) and 2) this would imply only one training is possible and user cannot train models in parallel. 
If the button needs to be reactivated in case of 3) the model page always needs to poll in current architecture.  This is even avoided in the validation page, if no training is ongoing when the page reloads, it doesn't poll to keep track of ongoing trainings (which is needed for the ongoing trainings panel).

Or if I recall correctly, you meant that the button should be disabled until the user recevies the training started feedback, because it takes a while currently. If that's the case I'm investigating why this is delayed in first place, so disabling the button may not be necessary after all if that resolves.
