### ISSUE TITLE
mobile recording issues

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#107]
I have tried recording  data with the mobile recording feature but I'm facing a number of issues.
- on Android, after I hit stop recording the dataset appears to have the timestamp at the unix start. trying to open the dataset crashes the browser
- on iOS it appears that the sensors can not be accessed

@tecoKIT

**Comment by omeryagmurlu** [comment]
Can you clarify the second issue? I've just tried with my ipad and everything works as intended. On iOS there are 2 sensors that we use and as long as your are not using an old iOS/Safari Version/device they should work.

What error do you get from the app? Which iOS version/device are you using?

**Comment by TobiasRoeddiger** [comment]
iphone 12, iOS15.5

**Comment by KtrauM** [comment]
I also tested with my iPad on iOS 14.8, I could capture data using the sensors however the starting date is set to unix start. 
Browser don't crash on me.
![image](https://user-images.githubusercontent.com/14796788/181517074-1441c7a5-fcdc-4eb2-b585-32861d466d64.png)

**Comment by TobiasRoeddiger** [comment]
Thanks, yes we have pinned the issue down:
- on iOS I was confused by the "Not available" for the sampling rate. We will change that to "Fixed"
- the issue with opening the dataset only exists on Android but not on iOS

**Comment by omeryagmurlu** [comment]
I'm not really sure about calling it fixed, because it's not really a fixed sampling rate. The sampling rate apparently depends on what the browser does at the moment (garbage collection etc). Sensor Api on safari is given such a low priority that even scrolling the page causes the sampling rate to fluctuate heavily. You can test it by scrolling while it's recording and then looking at how it affects the graph below

**Comment by TobiasRoeddiger** [comment]
Okay gotcha. Let‘s just hide the sampling rate column if it can not be changed.
