### ISSUE TITLE
bugs related to drawing labels

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#17]
it appears that there is currently an issue with drawing labels, I can not get it to work consistently - top priority atm besides the BLE feature

**Comment by ilteen** [comment]
Any details on how to reproduce? Seems to be working for me. I managed to produce a crash when deleting labels though, will look into that now.

**Comment by TobiasRoeddiger** [comment]
Primarily, if you click on the dot drawn on the chart where your cursor is. Probably just have to add an additional eventhandler for that case.

**Comment by TobiasRoeddiger** [comment]
also, I noticed that when the dot marker appears you can draw labels within labels. One solution may be to hide the marker for now and just keep the horizontal indicator.

**Comment by tk-king** [comment]
1. This can be done
2. The marker can be hidden
3. This is due to how a label is added. When clicking for the first time, a request to the backend is made. When you click the second time before this call returns the application crashes / unwanted behavior occurs. This might be hard to fix.
4. Another problem is, that you can draw labels over other labels.
![image](https://user-images.githubusercontent.com/30200721/133995735-9516b060-1467-4e9d-a94d-186d25a9a866.png)

**Comment by TobiasRoeddiger** [comment]
> 3. This is due to how a label is added. When clicking for the first time, a request to the backend is made. When you click the second time before this call returns the application crashes / unwanted behavior occurs. This might be hard to fix.
How about we only push the label to the backend after you click the second time? It's does not make a lot of sense to have a half defined label stored in the backend anyways.
> 4. Another problem is, that you can draw labels over other labels.
To some extent having labels on top of each other makes sense. Let's keep it for now and fix the other issues first.

**Comment by TobiasRoeddiger** [comment]
resolved for
