### ISSUE TITLE
caching results in unexpected behavior of the frontend

### ISSUE THREAD

**Issue by TobiasRoeddiger** [edge-ml/frontend#61]
after we push an update it happens again and again, that the react app is in a cached state. We need to find a way to control this better. E.g., clear cache after newly deployed version.

**Comment by tk-king** [comment]
- **Problem**: The problem seems to be comming from the react build system in combination with the default servieworker in the frontend. 

- **Solution**: Removed the  seriveworker and added code to remove existing serviceworkers form browsers that have already accessed the site.  

- **Notice**:  When a browser has already accessed the site before, the error will have to be resolved manually one more time which runs the code to get rid of the seriveworker.
